<a href="https://colab.research.google.com/github/whispermy/novatus_academia/blob/main/week1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 실습 2 - Python에서 텐서 데이터 다뤄보기

In [4]:
a = [1,2,3]
b = [4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

# 1. Numpy라는 툴(라이브러리)은 행렬 / 벡터 / 텐서 데이터의 수학적 연산에 적합

In [5]:
import numpy as np # Numpy 라이브러리를 np라는 이름으로 불러온다.

In [7]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [8]:
a + 2

array([3, 4, 5, 6])

In [9]:
b = np.array([5,6,7,8])
c = a+b
c

array([ 6,  8, 10, 12])

In [11]:
a = a*5
a

array([ 5, 10, 15, 20])

# 2. 다차원 array를 numpy로 구현하기

In [13]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

# 3. Numpy array 인덱싱 하기

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a[0]

array([1, 2, 3])

In [17]:
a[0,0] # 리스트와 다른 접근방식을 확인한다

1

# 4. Numpy array의 크기 파악하기

In [19]:
a = np.array([7,6,5,5,7,3,7])
np.shape(a)

(7,)

In [42]:
b = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
np.shape(b)

(2, 6)

In [43]:
a.shape
b.shape

(2, 6)

# 5. Array shape 변경하기 (2차원 -> 1차원)

reshape() / flatten() / ravel()

In [44]:
b.shape

(2, 6)

In [45]:
np.reshape(b,(12,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
b.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
np.ravel(b, order='C') # 행을 기준으로 합친다

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
np.ravel(b, order='F') # 열을 기준으로 합친다

array([ 1,  7,  2,  8,  3,  9,  4, 10,  5, 11,  6, 12])

# 6. 1 또는 0 으로 채워진 Array 만들어서 사용하기

In [53]:
one = np.ones(5)
zero = np.zeros(5)

In [54]:
one

array([1., 1., 1., 1., 1.])

In [55]:
zero

array([0., 0., 0., 0., 0.])

In [56]:
one2 = np.ones((2,3))

In [57]:
one2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [58]:
zero2 = np.zeros((5,5))

In [59]:
zero2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 7. Array 슬라이싱

In [60]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
a[1:,1:3]

array([[ 6,  7],
       [10, 11]])

# pop quiz: (10,10) 크기를 갖는 행렬의 가장자리가 1이고, 안쪽이 0값을 갖는 array를 만들어봅시다!

In [66]:
a = np.ones((10,10))
a[1:9,1:9] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [69]:
a = np.ones((10,10))
b = np.zeros((8,8))
a[1:9,1:9] = b
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# 8. 리스트에 range가 있다면, numpy는 arange

In [74]:
list(range(5))

[0, 1, 2, 3, 4]

In [75]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [76]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

# 9. Numpy의 Broadcasting

In [81]:
np.arange(3) + 5  # 0,1,2 에 5가 broadcasting되어서 각각 5씩 더해진다. 그래서 5,6,7로 나오게 된다.

array([5, 6, 7])

In [78]:
np.ones((3,3)) + np.arange(3) # 3x3 1행렬에 [0,1,2]인 3x1 행렬을 더하기 위해서 broadcasting 되어 각 행마다 [0,1,2] 가 더해진다.

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [80]:
np.arange(3).reshape((3,1)) + np.arange(3)  # 3x1 행렬에 [0,1,2]인 1x3 행렬을 더하기 위해서 각각 broadcasting 되어 각 행과 각 열마다 [0,1,2] 가 더해져서 아래와 같은 결과가 나온다.

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# 10. Array 끼리 이어붙이는 연산

In [82]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

In [83]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [85]:
# append
c = np.append(a,b, axis = 0) # 행을 기준으로 붙인다. 즉 a의 아래로 b가 붙는다.
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [86]:
c = np.append(a,b, axis = 1) # 열을 기준으로 붙인다. 즉 a의 우측에 b가 붙는다.
c

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# POP Quiz: 위 a,b를 가로로 붙였다가 flatten 한 후, (3,4) 형태로 reshape 한다.

In [91]:
d = np.append(a,b, axis = 1)
print('append:',d)
e = d.flatten()
print('flatten: ',e)
e.reshape((3,4))

append: [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
flatten:  [ 1  2  3  7  8  9  4  5  6 10 11 12]


array([[ 1,  2,  3,  7],
       [ 8,  9,  4,  5],
       [ 6, 10, 11, 12]])

# 11. 정해진 구간을 정해진 개수로 나누는 Array 만들기

In [92]:
a = np.linspace(0,10,5)
a


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# 12. Numpy를 이용하여 행렬 연산 쉽게하기

In [93]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[3,4,5],[6,7,8],[9,10,11]])

In [94]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
b

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [100]:
# 요소곱
a*b 
np.multiply(a,b)

array([[ 3,  8, 15],
       [24, 35, 48],
       [63, 80, 99]])

In [101]:
np.matmul(a,b) # 행렬곱을 수행할 땐 해당 함수를 사용한다. 

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

In [102]:
# 행렬의 가로와 세로를 대칭시키는 방법
np.transpose(a) 

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [114]:
c = a*b
print(c)
print(np.linalg.inv(c))
d = np.eye(3)
d_inv = np.linalg.inv(d)
d_inv

[[ 3  8 15]
 [24 35 48]
 [63 80 99]]
[[ 1.73611111 -1.88888889  0.65277778]
 [-3.          3.         -1.        ]
 [ 1.31944444 -1.22222222  0.40277778]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

break

In [104]:
f1 = np.array([6.1, 2.8, 4.7, 1.2])
w = np.array([0.043, 0.754, -0.767, 1.860])
c = f1*w
np.sum(c)

1.0006